// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iepuwaanaswqjxvarpht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllcHV3YWFuYXN3cWp4dmFycGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjg4MzYsImV4cCI6MjA2NzYwNDgzNn0.5m3XW4rT6EZqq71bRMbY-RWndtq5_wZiwGevVtf06Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});